{% set version = '0.9-36' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lmtest
  version: {{ version|replace("-", "_") }}

source:
  fn: lmtest_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lmtest_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lmtest/lmtest_{{ version }}.tar.gz
  sha256: be9f168d6554e9cd2be0f9d8fc3244f055dce90d1fca00f05bcbd01daa4ed56b

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: car, strucchange, sandwich, dynlm, stats4, survival, AER
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-zoo

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-zoo

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lmtest')"           # [not win]
    - "\"%R%\" -e \"library('lmtest')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=lmtest
  license: GPL-2 | GPL-3
  summary: A collection of tests, data sets, and examples for diagnostic checking in linear regression
    models. Furthermore, some generic tools for inference in parametric models are provided.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: lmtest
# Title: Testing Linear Regression Models
# Version: 0.9-36
# Date: 2018-04-04
# Authors@R: c(person(given = "Torsten", family = "Hothorn", role = "aut", email = "Torsten.Hothorn@R-project.org", comment = c(ORCID = "0000-0001-8301-0471")), person(given = "Achim", family = "Zeileis", role = c("aut", "cre"), email = "Achim.Zeileis@R-project.org", comment = c(ORCID = "0000-0003-0918-3766")), person(given = c("Richard", "W."), family = "Farebrother", role = "aut", comment = "pan.f"), person(given = "Clint", family = "Cummins", role = "aut", comment = "pan.f"), person(given = "Giovanni", family = "Millo", role = "ctb"), person(given = "David", family = "Mitchell", role = "ctb"))
# Description: A collection of tests, data sets, and examples for diagnostic checking in linear regression models. Furthermore, some generic tools for inference in parametric models are provided.
# LazyData: yes
# Depends: R (>= 2.10.0), stats, zoo
# Suggests: car, strucchange, sandwich, dynlm, stats4, survival, AER
# Imports: graphics
# License: GPL-2 | GPL-3
# NeedsCompilation: yes
# Packaged: 2018-04-03 22:53:11 UTC; zeileis
# Author: Torsten Hothorn [aut] (<https://orcid.org/0000-0001-8301-0471>), Achim Zeileis [aut, cre] (<https://orcid.org/0000-0003-0918-3766>), Richard W. Farebrother [aut] (pan.f), Clint Cummins [aut] (pan.f), Giovanni Millo [ctb], David Mitchell [ctb]
# Maintainer: Achim Zeileis <Achim.Zeileis@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-04-04 08:13:09 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
