travis:
  secure:
    BINSTAR_TOKEN: RO1RQchFKyf3F+gOpVgGQilhlzSmOGxhgnmYNpIyNCYvuCEYAm40odeesd/KL3DqS0xa4m1v4gRBZgvLPKdXWX8YPdOBstKVdRg5gtIWVRGwmBgxVuPFLKecusfybSJqSULJwTqoVGYUFbGHDunHHN7NZOyqVOghEgik4VsirC+8WmrCetPcv0Xp/4Eaks6IaNQBFYTkT7ccZm/t6qbXkY034+D7I7GP6hNmJzKYO1pPGKzZts+KWkmIIQIskFi43BALx4pZ/C/6yM4suSEDfX1W4RN6CBwftVQjerura0Zk9nNaCwtf3LrUGDilek3OP3IHDTnNustmtQsCHIT/W9QvilrJ45rp9bsPUwVV40iC2KzaKT+2K1IOTReRDnDnwglupkA433Jzw91hpXdBQonojTLCfed4wzaAYEO68LkFa8rvXAwYlOHsD25okmqGIvBhIFaoYbVcsf6ITLQzTmHVl2Dvp/6OLQiynScHjLRTAFVvtC7d6rjElcU0KJHcpBCIP3jCre3nuuC3V8Pj38tW0rz+n4BuXf5IWm3GGSzxLjQh8lIN1xBWzG2L14Pl30NXKgG4wO08yGanVLqT5gVylpQQ+vkub6AVpx7lca8ehku+N3c4IxU3NvsamqyXsjrlklUayrCKAVbdNGa6+C6lGyEfz8OmmkyVmihiNNI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
