travis:
  secure:
    BINSTAR_TOKEN: DezMman6RMVfeZN8UCSdRsxZnzRL9buWHeP2qow5z/1kZFTUBE0W2y5bGUx/p00my5OEMjyRNMgEnPjWeSSGhketZQRsExlmsaeywFDqj0/A7NWYfkbO3Z1SKEm4NVleilmwqkSG8ZucFCJJS0vidQlseGRTM9LiHcce2y/tN9xXiMEScv/b167VJf5g0EFjGBr0FIjsArFHLO4uaViIkz3fGEYtYbvwmPpuAXfjujrITD9UFJ6ENKc5YzVnlcz1MqKrZ27deR2asXserGBO4pkB0Zfdz7dgmdeGiHBZanTSV/vKtNY2YHG0/ZHqWP7AWDCWwE/oHiAlO7KcfjbQvKJu5eGodhq6GJHPAHKCACKBQPlcKugA0ec7pTe3hvlx1TWGn+diWUDeiH0I//MtE1Se7g/o94Z1p0n/zG56M5JsSBa1BoqvST6+oAoK6L9nSDbLTa34krx2uyfPiUegyhK/qKBrwPXkmhrI6HFhdB9R1CLjwqF1s/RwK8xQ4qdXhGPHUB51tpYB6HWi7X++CJ81E1Tf5ddB3TsTllPYa6vLQQkWpeTEygyeBFfHsQZdjo8jjZ2mUr0899FErPsVVEMcrYH7kSFgO8rJk9DLuMGua/67PsAB6hgk6XHyHkErKSE12RNbbLcpHTp7eOJQPtjHa3y7hdjMOTNajgzOKn4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
